---
safe: false
baseurl: /
url: http://localhost:4000
source: .
destination: ./_site
plugins: ./_plugins
timezone: 'America/Denver'
include:
  - 'css/'
exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'bin/'
  - 'extract.rb'
future: true
lsi: false
pygments: true
markdown: rdiscount
permalink: none
paginator: true
paginate: 5
encoding: utf-8
rdiscount:
  extensions: []
sass:
  syntax: scss
  style: compressed
