---
safe: false
auto: true
server: false
server_port: 4000
baseurl: /
url: http://localhost:4000
source: .
destination: ./_site
plugins: ./_plugins
include:
  - 'stylesheets/'
exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'bin/'
  - 'extract.rb'
future: true
lsi: false
pygments: true
markdown: rdiscount
permalink: none
paginator: true
paginate: 5
rdiscount:
  extensions: []
sass:
  syntax: scss
  style: expanded
