---
safe: false
baseurl: /
url: http://localhost:4000
source: .
destination: ./_site
plugins:
  - bundler
  - jekyll-paginate
timezone: 'America/Denver'
include:
  - 'css/'
exclude:
  - 'Rakefile'
  - 'Gemfile'
  - 'Gemfile.lock'
  - '_ideas.md'
future: true
lsi: false
highlighter: rouge
markdown: redcarpet
permalink: none
paginator: true
paginate: 5
encoding: utf-8
rdiscount:
  extensions: []
sass:
  style: expanded
  deploy_style: compressed
